### ISSUE TITLE
How add custom button?

### ISSUE THREAD

**Issue by ShockWave2048** [snmslavk/WPF-Keyboard-Control#15]
Hi Viacheslav!
How i can add custom button?
I need place button with "@" symbol, in left side of Space Key.
What need to do for this?
(Have installed WWPF-Keyboard-Control as NuGet extension)
And second small question - how change style of all buttons? (like android keys dark theme)
Thanks for answers!

**Comment by snmslavk** [comment]
Hi,

Here you can find the information about buttons and add additional buttons https://github.com/snmslavk/WPF-Keyboard-Control/blob/master/TermControls/Models/KeyboardModelRuEng.cs

Here https://github.com/snmslavk/WPF-Keyboard-Control/tree/master/TermControls/Images
you can find all images for buttons, just replace the images that you want to change

**Comment by snmslavk** [comment]
If you have any other questions I'll reopen it. For now it's closed.
