### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by abooch** [snmslavk/WPF-Keyboard-Control#2]
Hello,
Why it is not working if i`m trying to bind Keyboard to textbox?

example:

```
<TextBox Name="txtName"></TextBox>
<TermControls: Text="{Binding UserName, ElementName=txtName}"></TermControls:OnScreenKeyboard>
```

**Comment by snmslavk** [comment]
Hi,

I cannot imagine the reasons why you are trying to do it. 

If you want to bind textbox to keyboard just type this

`<TextBox Text="{Binding Text, ElementName=onScreenKeyboard}" Name="txtName" />`

**Comment by abooch** [comment]
Ok, The real example is:
I have 2 controls textbox and keyboard and datacontext class that have UserName property, so i need to bind both of controls to that property. The binding of Keyboard is not working.

```
<TextBox Text="{Binding UserName, UpdateSourceTrigger=PropertyChanged}"  Name="txtName"></TextBox>
<TermControls:OnScreenKeyboard  Name="ScreenKeyboard"  Text="{Binding UserName, UpdateSourceTrigger=PropertyChanged}" ></TermControls:OnScreenKeyboard>
```

Or maybe you could tell me how to fix it?

**Comment by snmslavk** [comment]
Yes, this problem exists. Honestly, I don't know whether it's a usercontrol issue or it's just inappropriate usage of binding.
Now,it's a really high load period at my work, so I'll fix this later. If you've already found a solution, you could leave comment here.

Best regards.

**Comment by abooch** [comment]
Actually this is a binding issue.
You have a Setter, that is already binded to internal field inside model. Binding it to another field deletes that binding.
I've fixed it by moving click methods to xaml and working with text property inside the methods. I think that this is not coorect to work this way, but for me it just works. :)
