### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by TorKlingberg** [snmslavk/WPF-Keyboard-Control#3]
```
PS C:\Users\tmk> Install-Package WPFTouchKeyboard
Install-Package : No match was found for the specified search criteria and package name 'WPFTouchKeyboard'.
```

**Comment by snmslavk** [comment]
Hi,

It should be ok, here the link at nuget website https://www.nuget.org/packages/WPFTouchKeyboard

**Comment by TorKlingberg** [comment]
Sorry, I was in the regular Powershell. I should be in the Nuget console. It's under Tools --> NuGet Package Manager.
