### ISSUE TITLE
Hide the yellow button

### ISSUE THREAD

**Issue by TorKlingberg** [snmslavk/WPF-Keyboard-Control#4]
Hi. Can I hide the yellow button with Russian text on?

**Comment by snmslavk** [comment]
Hey,there is no a yellow button, what do you mean?

**Comment by TorKlingberg** [comment]
![This one](https://cloud.githubusercontent.com/assets/227449/17360251/91e68e64-5962-11e6-8017-f5031c6e65c3.png)

**Comment by snmslavk** [comment]
I downloaded it now and It looks different for me and without this yellow button. It is strange.
https://gyazo.com/cb02c1283f509481a07f7be885ec287d

**Comment by TorKlingberg** [comment]
Yes, very strange. I will just put a solid white rectangle on top as a workaround.
