### ISSUE TITLE
Other Languages

### ISSUE THREAD

**Issue by ChrisMoney** [snmslavk/WPF-Keyboard-Control#5]
Can I configure the keyboard to display any languages other than English and Russian?

**Comment by snmslavk** [comment]
Hi. Of course you can, just create new KeyboardModel, for example now this control uses KeyboardModelRuEng, you need to create new one and replace ru-eng model.

**Comment by ChrisMoney** [comment]
I'm so sorry but I cannot find any documentation on how to create a new keyboard model object. Could you give em an example of how I would create a Spanish keyboard model instance?

-------- Original Message --------
Subject: Re: [snmslavk/WPF-Keyboard-Control] Other Languages (#5)

**Comment by snmslavk** [comment]
Create new class and inherit it from KeyboardModel, then replace this line in KeyboardViewModel.cs
`this.Model = new YourNewModelEspEng();`

**Comment by ChrisMoney** [comment]
Okay, so I have your entire project added to my solution; but now I cannot get a keypress event on the virtual keyboard to bind to my textbox. I see the Text get and set the value in the Keyboard model, but it just won't appear on screen. Any ideas?

**Comment by snmslavk** [comment]
It's hard to help you blindly when I don't have your code, don't now what kind of exception you get and etc. My idea is that in this repo there is a working example of usage this control, just download and do the magic that is described above and all should work.
